### ISSUE TITLE
Skopy crashes with IndexError when no ORB features could be detected 

### ISSUE THREAD

**Issue by cells2numbers** [broadinstitute/skopy#6]
```
wm80f-1a4:label tbecker$ time skopy measure 2014_07_08.csv
  [------------------------------------]    1%
Traceback (most recent call last):
  File "/usr/local/bin/skopy", line 11, in <module>
    load_entry_point('skopy', 'console_scripts', 'skopy')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/tbecker/repos/skopy/skopy/commands/command_measure.py", line 51, in command
    image = skopy.feature.extract(pathname, mask)
  File "/Users/tbecker/repos/skopy/skopy/feature/__init__.py", line 40, in extract
    image.descriptions = describe(x_data)
  File "/Users/tbecker/repos/skopy/skopy/feature/__init__.py", line 27, in describe
    description = Description.measure(index, descriptor)
  File "/Users/tbecker/repos/skopy/skopy/feature/_description.py", line 28, in measure
    "keypoint_x": descriptor.keypoints[index][0],
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by bethac07** [comment]
This feature was removed.
